export Excel
export file_sse
export file_labs
export Nombre_Proyecto
export Nombre_Area
export Codigo_Proyecto
export Nombre_Solicita
export Fecha_Solicita
export Fecha_Entrega
export Posicion_base
export Posicion_ME
export Posicion_EQMAT
export Posicion_OBS
export Posicion_ADJ
export N_filas
export Cant_lab
export N_Lab
export elementos
export this_matriz_estaciones
export N_matrices
export Equipos
export arrays
export str_laboratorios
export str_limites
export str_matriz
export str_this_matrices
export "export"
